"""Additional paired metric audit for the paper's primary task metrics.

Usage: python metric_audit.py --frame /path/to/GraphTalk/csv2/raw-trends/frame.csv
The input is generated by `scripts/build_raw_frame.py` on results-sot.
The source is unmodified; this script documents the supplemental calculations.
"""

import argparse

import numpy as np
import pandas as pd

PRIMERS = ("filler", "components", "clustering", "rwse", "degree", "all")
ARMS = ("qwen3-1.7b", "qwen3-1.7b-think", "qwen3-4b", "qwen3-4b-think")
RNG = np.random.default_rng(20260925)


def paired_values(frame, arm, task, condition):
    rows = frame[(frame.arm == arm) & (frame.task == task) & (frame.density_class <= 0.5)]
    before = rows[rows.condition == "none"].set_index("instance_id").sort_index()
    after = rows[rows.condition == condition].set_index("instance_id").sort_index()
    assert len(before) == len(after) == 400
    assert before.index.is_unique and after.index.is_unique
    assert before.index.equals(after.index)
    assert np.array_equal(before.gold.values, after.gold.values)
    # Truncated output has its own outcome; assign zero primary score so all
    # pairwise contrasts use the full common set of graph prompts.
    base = before.f1.to_numpy() * (1 - before.hit_cap.to_numpy())
    primed = after.f1.to_numpy() * (1 - after.hit_cap.to_numpy())
    return base, primed


def paired_sign_p(diff, draws=50000):
    observed = abs(diff.mean())
    extreme = 0
    for _ in range(draws // 5000):
        signs = RNG.integers(0, 2, size=(5000, len(diff)), dtype=np.int8) * 2 - 1
        extreme += np.count_nonzero(abs((signs * diff).mean(axis=1)) >= observed - 1e-12)
    return (extreme + 1) / (draws + 1)


def bh(pvals):
    order = np.argsort(pvals)
    result = np.empty(len(pvals))
    sorted_q = np.minimum.accumulate(
        (np.array(pvals)[order] * len(pvals) / np.arange(1, len(pvals) + 1))[::-1]
    )[::-1]
    result[order] = np.minimum(sorted_q, 1)
    return result


def interval(diff, draws=10000):
    samples = RNG.integers(0, len(diff), size=(draws, len(diff)))
    return np.percentile(diff[samples].mean(axis=1), [2.5, 97.5])


def report(frame):
    print("[metric-audit-f1] Paired mean Set-F1 on all 400 prompts per arm/condition;")
    print("truncations assigned F1=0; random-sign paired p (50k draws),")
    print("BH q within arm across six primers; paired graph bootstrap CI (10k draws).")
    for arm in ARMS:
        metrics = []
        for condition in PRIMERS:
            before, after = paired_values(frame, arm, "connected_nodes", condition)
            d = after - before
            metrics.append((condition, before.mean(), after.mean(), d.mean(), paired_sign_p(d), d))
        qs = bh([entry[4] for entry in metrics])
        for (condition, base, new, delta, p, d), q in zip(metrics, qs):
            lo, hi = interval(d)
            print(f"  {arm:20s} {condition:10s} {base:.4f}->{new:.4f} "
                  f"delta={delta:+.4f} CI=[{lo:+.4f},{hi:+.4f}] p={p:.5f} q={q:.5f}")

    print("[metric-audit-edge] Plain Qwen3-1.7B, edge existence, dense extension;")
    print("raw accuracy and balanced accuracy use all prompts, yes-rate finished only.")
    for density in (0.65, 0.75, 0.85):
        for condition in ("none", "all"):
            x = frame[(frame.arm == "qwen3-1.7b") & (frame.task == "edge_existence")
                      & (frame.density_class == density) & (frame.condition == condition)]
            assert len(x) == 100
            correct = x.exact * (1 - x.hit_cap)
            positive = x.gold_is_yes == 1
            ba = (correct[positive].mean() + correct[~positive].mean()) / 2
            finished = x[x.hit_cap == 0]
            yes = (finished.pred == "Yes").mean()
            print(f"  p={density:.2f} {condition:4s} raw={correct.mean():.3f} "
                  f"BA={ba:.3f} yes={yes:.3f} truncated={x.hit_cap.mean():.3f}")

    print("[metric-audit-edge-main] Edge existence, main sweep, all model arms;")
    print("raw and balanced accuracy use all prompts, yes-rate finished only.")
    for arm in ("qwen3-1.7b", "qwen3-1.7b-think", "qwen3-4b", "qwen3-4b-think"):
        for condition in ("none", "degree", "clustering", "rwse", "all"):
            x = frame[(frame.arm == arm) & (frame.task == "edge_existence")
                      & (frame.density_class <= 0.5) & (frame.condition == condition)]
            assert len(x) == 400
            correct = x.exact * (1 - x.hit_cap)
            positive = x.gold_is_yes == 1
            ba = (correct[positive].mean() + correct[~positive].mean()) / 2
            finished = x[x.hit_cap == 0]
            yes = (finished.pred == "Yes").mean()
            print(f"  {arm:20s} {condition:10s} raw={correct.mean():.4f} "
                  f"BA={ba:.4f} yes={yes:.4f} truncated={x.hit_cap.mean():.4f}")

    print("[metric-audit-edge-errors] Main-sweep confusion counts on matched queries;")
    print("prevalence is the common fraction of positive gold labels.")
    for arm, primers in (("qwen3-1.7b", ("none", "all")),
                         ("qwen3-4b", ("none", "rwse"))):
        for condition in primers:
            x = frame[(frame.arm == arm) & (frame.task == "edge_existence")
                      & (frame.density_class <= 0.5) & (frame.condition == condition)]
            positive = x.gold_is_yes == 1
            fp = ((x.pred == "Yes") & ~positive & (x.hit_cap == 0)).sum()
            tp = (positive & (x.exact == 1) & (x.hit_cap == 0)).sum()
            print(f"  {arm:20s} {condition:4s} prevalence={positive.mean():.4f}"
                  f" false_positives={fp} true_positives={tp}"
                  f" positive_total={positive.sum()} truncated={x.hit_cap.sum()}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--frame", required=True)
    args = parser.parse_args()
    report(pd.read_csv(args.frame))
