"""The shared difficulty ladder: one corpus every model runs, with each model
analysed only on the rungs where it has headroom.

Why a ladder and not a cell. Scored across every corpus on disk, `base30` is
1.000 for qwen3-8b, gemma4-e4b, gemma4-12b and qwen3-14b simultaneously, while
qwen3-1.7b sits at 0.890 -- saturated for everything from 8B up. Meanwhile the
`size20/40/80` corpus puts qwen3-1.7b in its informative band at size40 (0.440)
and qwen3-8b at size80 (0.479), on the *same graphs*. No single cell can be
informative for both a 0.6B and a 14B; a ladder can, and each model's analysis
is then restricted to its own rungs.

Why two axes. `n` is the length axis and `mean_degree` the answer-magnitude
axis, and they produce difficulty with opposite implications for primers:

  * Length-limited (large `n`, low degree): the model cannot read the graph, and
    cannot use a primer either -- where the plain arm collapses, the `degree`
    control that writes the answer verbatim into the prompt is worth +0.7pp.
  * Magnitude-limited (moderate `n`, high degree): the model reads everything
    and miscounts, which is exactly the work a primer short-circuits -- the same
    control is worth +6.8pp there.

A one-dimensional size ladder can only ever place a model in the first regime.
This one lets each model be placed in the second at its own difficulty, which is
the only regime where a primer effect is a claim about primer *content*.

The rungs below were selected from a 45-cell screen (`cell_screen`) over
n in 20..400 and mean degree 4..24. Two boundaries came out of that screen and
are worth stating, because both are findings rather than conveniences:

  * **n=20 is dead at every degree** -- `maj_base` 0.287-0.325, so a blind
    guesser wins roughly a third of the time. Too few nodes means too few
    distinct degree values.
  * **Structure stops being the binding constraint above n~120.** Nearly every
    large cell passes the blind and silent screens; what excludes them is
    reading limit and context window. That inverts the usual assumption that
    big graphs are structurally awkward -- they are structurally fine and
    simply too long.

Token counts are for qwen3's tokenizer with the `none` condition. The `all`
primer roughly doubles them, so `context_headroom` must be checked against the
condition actually being run, not against these numbers.
"""

# (n, mean_degree, tokens_none) -- tokens measured, not estimated, with the real
# tokenizer plus the 12-token plain chat-template overhead. Regenerated by
# `scripts/build_ladder.py --screen`; `tests/test_ladder.py` checks these stay
# in step with `cell_screen`, so an unintended drift here fails a test rather
# than silently reshaping every downstream run.
RUNGS = (
    (40, 8, 1691),
    (80, 4, 2197),
    (40, 12, 2290),
    (60, 8, 2569),
    (40, 16, 2893),
    (120, 4, 3430),
    (80, 8, 3448),
    (60, 12, 3489),
    (60, 16, 4407),
    (80, 12, 4688),
    (120, 8, 5409),
    (80, 16, 5931),
    (120, 12, 7373),
    (160, 8, 7576),
    (120, 16, 9344),
    (160, 12, 10330),
    (200, 12, 13277),
    (300, 8, 15136),
)

# Reading regimes measured on qwen3-1.7b with a graph-free retrieval probe
# (job 871909): retrieval is perfect to ~1,500 tokens, degraded by 3,105, and by
# 6,305 the middle of the prompt is read 19.5% of the time against 89% at the
# ends. These are BRACKETS, not thresholds -- the crossings were never located,
# and they are measured for one model. `reading_zone` therefore returns a
# regime name, not a pass/fail, and every model needs its own probe.
READING_CLEAN = 1505
READING_DEGRADED = 3105
READING_MIDDLE_COLLAPSE = 6305


def reading_zone(tokens: int) -> str:
  """Which measured reading regime a prompt length falls in, for qwen3-1.7b."""
  if tokens <= READING_CLEAN:
    return "clean"
  if tokens <= READING_DEGRADED:
    return "bracket-1"      # threshold known to be in here, never located
  if tokens <= READING_MIDDLE_COLLAPSE:
    return "bracket-2"      # middle-collapse known to be in here
  return "collapsed"


def context_headroom(tokens: int, max_context: int, max_new: int) -> int:
  """Spare context after the prompt and the generation budget.

  Negative means the row would be skipped by `hf_backend`'s overflow guard
  before generating anything -- which is how an earlier sweep produced 35 rows
  of `overflow: true` that were then misread as output truncation.
  """
  return max_context - max_new - tokens


def feasible_rungs(max_context: int, max_new: int, primer_multiplier: float = 2.0):
  """Rungs that fit in context for a given arm, with the primer's cost included.

  `primer_multiplier` defaults to 2.0 because the `all` primer roughly doubles
  prompt length; pass 1.0 to check the `none` condition alone.
  """
  return tuple(
      (n, degree, tokens) for n, degree, tokens in RUNGS
      if context_headroom(int(tokens * primer_multiplier), max_context, max_new) >= 0
  )


def classify_band(accuracy: float, ceiling: float = 0.90,
                  floor: float = 0.20) -> str:
  """Where a model sits on one rung.

  Only `informative` rungs carry a primer test: a ceiling rung has no room to
  improve and a floor rung has no room to fall, and in both cases a null result
  is uninterpretable rather than evidence of no effect.
  """
  if accuracy >= ceiling:
    return "ceiling"
  if accuracy <= floor:
    return "floor"
  return "informative"


def model_band(accuracies: dict, reading_limit: int | None = None) -> dict:
  """Given one model's accuracy per rung, the rungs where a primer can be tested.

  `accuracies` maps `(n, mean_degree)` to that model's `none` accuracy.
  `reading_limit` is per model AND per arm -- there is deliberately no default,
  because using qwen3-1.7b's brackets for another model is exactly the mistake
  this whole design exists to avoid.
  """
  rows = []
  for n, degree, tokens in RUNGS:
    accuracy = accuracies.get((n, degree))
    if accuracy is None:
      continue
    band = classify_band(accuracy)
    readable = reading_limit is None or tokens <= reading_limit
    rows.append({
        "n": n,
        "mean_degree": degree,
        "tokens": tokens,
        "accuracy": accuracy,
        "band": band,
        "readable": readable,
        "valid": band == "informative" and readable,
    })
  return {
      "rungs": rows,
      "valid": [r for r in rows if r["valid"]],
      "informative_but_unreadable": [
          r for r in rows if r["band"] == "informative" and not r["readable"]
      ],
  }
