"""Emit the generated tables of talk_like_a_graph.v3.tex into paper/.

Every output is prefixed `v3_` -- note that paper/degfixdeg_table.tex and
paper/short/degfixdeg_table.tex are already two different files from two
different generators, and this script must not add a third collision.

  tab:main        every pooled effect against `none`, 4 arms x 4 tasks (body)
  tab:conditions  the seven conditions: content, length, answer-carrying (body)
  tab:pertask-*   the two constant-gold tasks (appendix)
  tab:routes      procedure and accuracy on node_degree by density (appendix)

Reads csv2/raw-trends/ only. frame.csv is the per-response frame that
scripts/build_raw_frame.py rebuilds from runs/ (and whose golds it verifies
against the stored ones); node_degree_routes.csv comes from
scripts/primer_findings.py. Pairing: pair on the shared graph, drop a pair if
either side hit the generation budget, exact match, exact McNemar,
Benjamini-Hochberg within each (arm, task) family.

  PYTHONPATH=. python paper/make_v3_tables.py
"""
import json

import numpy as np
import pandas as pd

from graphtalk import scoring

OUT = "paper/"
SRC = "csv2/raw-trends/"
BARS = "shortcuts_n40_flat.json"
ARMS = ["qwen3-1.7b", "qwen3-1.7b-think", "qwen3-4b", "qwen3-4b-think"]
SHORT = {"qwen3-1.7b": "1.7B", "qwen3-4b": "4B",
         "qwen3-1.7b-think": "1.7B-think", "qwen3-4b-think": "4B-think"}
CONDS = ["components", "clustering", "rwse", "degree", "all"]
# The four densities every task was run at. node_degree and edge_existence also
# have .65/.75/.85; pooling those in would make the columns mean different
# things task to task, so the pooled tables stay on the shared four.
DENS4 = [0.10, 0.20, 0.35, 0.50]
SHOWN = ["edge_existence", "node_degree", "connected_nodes", "edge_count"]
ABBR = {"edge_existence": "exist.", "node_degree": "deg.",
        "connected_nodes": "conn.", "edge_count": "count"}
# Gold is the same for every graph at n=40, so a shift on these need not be
# graph reading. They get their own appendix tables.
CONST_GOLD = ["node_count", "cycle_check"]
CARRIES = 0.85


def tex(s):
    return str(s).replace("_", r"\_")


def write(name, lines):
    with open(OUT + name, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote " + OUT + name)


def bh(pvals):
    """Benjamini-Hochberg q-values, order preserved. NaN passes through."""
    p = np.asarray(pvals, dtype=float)
    q = np.full_like(p, np.nan)
    ok = ~np.isnan(p)
    if not ok.any():
        return q
    pv, n = p[ok], int(ok.sum())
    order = np.argsort(pv)
    ranked = pv[order] * n / np.arange(1, n + 1)
    # Enforce monotonicity from the largest p down, so a small p can never get a
    # larger q than a bigger one.
    ranked = np.minimum.accumulate(ranked[::-1])[::-1]
    out = np.empty(n)
    out[order] = np.clip(ranked, 0, 1)
    q[ok] = out
    return q


def load_frame():
    f = pd.read_csv(SRC + "frame.csv")
    return f[f.density_class.isin(DENS4)]


def paired(frame, arm, task, baseline, cond):
    """Pooled paired contrast on the shared graphs. Returns (delta_pts, p, n)."""
    d = frame[(frame.arm == arm) & (frame.task == task)]
    a = d[d.condition == baseline].set_index("graph_id")
    b = d[d.condition == cond].set_index("graph_id")
    j = a.join(b, lsuffix="_a", rsuffix="_b", how="inner")
    j = j[(j.hit_cap_a == 0) & (j.hit_cap_b == 0)]
    if len(j) < 10:
        return np.nan, np.nan, len(j)
    m = scoring.mcnemar(j.exact_a.astype(bool), j.exact_b.astype(bool))
    delta = 100.0 * (j.exact_b.mean() - j.exact_a.mean())
    return delta, m["p_value"], len(j)


# Below this many surviving pairs a cell is reported but never bolded: the
# survivors are selected on a post-treatment outcome (whether the generation
# terminated), so a significant McNemar there is not interpretable as a primer
# effect. Every such cell in this sweep is a thinking-arm `edge_count` cell.
N_FLOOR = 100


def cell(delta, q, n):
    if np.isnan(delta):
        return "--"
    body = f"{delta:+.1f}"
    if not np.isnan(q) and q < 0.05 and n >= N_FLOOR:
        return r"$\mathbf{" + body + "}$"
    return f"${body}$"


def contrasts(frame, arm, task):
    """Accuracy under none, and every primer's paired effect with its BH q."""
    d = frame[(frame.arm == arm) & (frame.task == task)]
    b = d[(d.condition == "none") & (d.hit_cap == 0)]
    vn = ["filler"] + CONDS
    res = {c: paired(frame, arm, task, "none", c) for c in vn}
    qs = dict(zip(vn, bh([res[c][1] for c in vn])))
    return 100.0 * b.exact.mean(), res, qs


# ------------------------------------------------------------------ tab:main
def main_table(frame):
    """Every pooled effect against `none`, one column per (arm, task)."""
    vn = ["filler"] + CONDS
    cols = [(a, t) for a in ARMS for t in SHOWN]
    got = {k: contrasts(frame, *k) for k in cols}
    ncol = len(cols)
    lines = [r"% Auto-generated by paper/make_v3_tables.py -- do not hand-edit.",
             r"\begin{table*}[t]", r"\centering", r"\small",
             r"\setlength{\tabcolsep}{2.6pt}",
             r"\resizebox{\textwidth}{!}{%",
             r"\begin{tabular}{l" + "r" * ncol + "}", r"\toprule",
             " & " + " & ".join(r"\multicolumn{4}{c}{\texttt{" + tex(a) + "}}"
                                for a in ARMS) + r" \\",
             "".join(r"\cmidrule(lr){%d-%d}" % (2 + 4 * i, 5 + 4 * i)
                     for i in range(len(ARMS))),
             " & " + " & ".join(ABBR[t] for _, t in cols) + r" \\",
             r"\midrule",
             r"\texttt{none} (acc.) & " + " & ".join(
                 f"{got[k][0]:.1f}" for k in cols) + r" \\"]
    nrow = []
    for k in cols:
        lo = min(got[k][1][c][2] for c in vn)
        nrow.append(f"{lo}" if lo >= N_FLOOR else r"\textit{" + f"{lo}" + "}")
    lines += ["pairs & " + " & ".join(nrow) + r" \\", r"\midrule"]
    for c in vn:
        lines.append(r"\texttt{" + c + "} & " + " & ".join(
            cell(got[k][1][c][0], got[k][2][c], got[k][1][c][2]) for k in cols)
            + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}}",
              r"\caption{Pooled effects against \texttt{none} (points), "
              r"$p\le.50$, $100$ graphs per (task, density). Tasks: "
              r"\texttt{edge\_existence} (exist.), \texttt{node\_degree} (deg.), "
              r"\texttt{connected\_nodes} (conn.), \texttt{edge\_count} (count). "
              r"First row: accuracy under \texttt{none} over terminated "
              r"generations; \emph{pairs}: fewest pairs in which neither "
              r"generation truncated. \textbf{Bold}: exact McNemar, "
              r"Benjamini--Hochberg over each column's six contrasts, $q<.05$; "
              r"columns with \textit{italic} pair counts (below $100$) are never "
              r"bolded, since their survivors are selected on termination.}",
              r"\label{tab:main}", r"\end{table*}"]
    write("v3_main_table.tex", lines)


# ------------------------------------------------------------ tab:conditions
def conditions(frame):
    """What each condition states, how long it is, where it carries the answer."""
    bars = json.load(open(BARS, encoding="utf-8"))
    chars = frame.groupby("condition").primer_chars.mean()
    what = {
        "none": "no primer",
        "components": "component count",
        "degree": "degree",
        "clustering": "clustering coefficient",
        "rwse": "return prob., 2 and 3 steps",
        "all": "the three rows above",
        "filler": r"``Node $i$ is simply present''",
    }
    lines = [r"% Auto-generated by paper/make_v3_tables.py -- do not hand-edit.",
             r"\begin{table}[t]", r"\centering", r"\small",
             r"\setlength{\tabcolsep}{2.4pt}",
             r"\begin{tabular}{@{}llrl@{}}", r"\toprule",
             r"Condition & States & Chars & Carries \\", r"\midrule"]
    for c in ["none", "components", "degree", "clustering", "rwse", "all",
              "filler"]:
        carry = [ABBR[t] for t in SHOWN
                 if bars.get(f"{t}/{c}", 0.0) >= CARRIES]
        n = "--" if c == "none" else f"{chars[c]:,.0f}"
        lines.append(r"\texttt{" + c + "} & " + what[c] + f" & {n} & "
                     + (", ".join(carry) if carry else "--") + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}",
              r"\caption{The seven conditions. \emph{States}: what each primer "
              r"gives per node (\texttt{components}: for the graph). "
              r"\emph{Chars}: mean primer "
              r"length in characters. \emph{Carries}: tasks with variable gold "
              r"on which the graph-blind solver scores at least "
              r"$0.85$ (Appendix Table~\ref{tab:shortcut}); abbreviations as "
              r"in Table~\ref{tab:main}.}",
              r"\label{tab:conditions}", r"\end{table}"]
    write("v3_conditions_table.tex", lines)


# -------------------------------------------------------------- tab:pertask
def per_task(frame):
    """The two constant-gold tasks: accuracy under none and every effect."""
    lines = [r"% Auto-generated by paper/make_v3_tables.py -- do not hand-edit.",
             r"\begin{table}[H]", r"\centering", r"\small",
             r"\setlength{\tabcolsep}{3.4pt}",
             r"\resizebox{\columnwidth}{!}{%",
             r"\begin{tabular}{lrrrrrrr}", r"\toprule",
             r"Arm & \texttt{none} & filler & comp. & clust. & rwse & "
             r"degree & all \\"]
    for task in CONST_GOLD:
        lines += [r"\midrule",
                  r"\multicolumn{8}{@{}l}{\texttt{" + tex(task) + r"}} \\"]
        for arm in ARMS:
            base, res, qs = contrasts(frame, arm, task)
            lines.append(tex(SHORT[arm]) + f" & {base:.1f} & " + " & ".join(
                cell(res[c][0], qs[c], res[c][2])
                for c in ["filler"] + CONDS) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}}",
              r"\caption{The two tasks with constant gold at $n{=}40$, "
              r"pooled over $p\le.50$: accuracy under \texttt{none} (\%) and "
              r"paired effects against it (points). \textbf{Bold}: as in "
              r"Table~\ref{tab:main}.}",
              r"\label{tab:constgold}", r"\end{table}"]
    write("v3_pertask_tables.tex", lines)


# --------------------------------------------------------------- tab:routes
def routes():
    """How the model uses the degree on node_degree, by density."""
    r = pd.read_csv(SRC + "node_degree_routes.csv")
    dens = sorted(r.density.unique())

    def row(label, arm, cond, col):
        s = r[(r.arm == arm) & (r.condition == cond)].set_index("density")
        vals = []
        for d in dens:
            v = s.loc[d, col] if d in s.index else np.nan
            vals.append("--" if pd.isna(v) else f"{100 * v:.0f}")
        return label + " & " + " & ".join(vals) + r" \\"

    lines = [r"% Auto-generated by paper/make_v3_tables.py -- do not hand-edit.",
             r"\begin{table}[H]", r"\centering", r"\small",
             r"\setlength{\tabcolsep}{2.6pt}",
             r"\begin{tabular}{l" + "r" * len(dens) + "}", r"\toprule",
             r"$p$ & " + " & ".join(f"{d:.2f}".lstrip("0") for d in dens)
             + r" \\", r"\midrule",
             r"\multicolumn{%d}{@{}l}{\texttt{qwen3-4b}} \\" % (len(dens) + 1),
             row(r"acc., \texttt{none}", "qwen3-4b", "none", "acc"),
             row(r"acc., \texttt{degree}", "qwen3-4b", "degree", "acc"),
             row(r"\quad retrieves", "qwen3-4b", "degree", "share_retrieve"),
             row(r"\quad acc.\ of retrievals", "qwen3-4b", "degree",
                 "acc_retrieve"),
             row(r"acc., \texttt{all}", "qwen3-4b", "all", "acc"),
             row(r"\quad retrieves", "qwen3-4b", "all", "share_retrieve"),
             row(r"\quad acc.\ of retrievals", "qwen3-4b", "all",
                 "acc_retrieve"),
             r"\midrule",
             r"\multicolumn{%d}{@{}l}{\texttt{qwen3-1.7b-think}} \\"
             % (len(dens) + 1),
             row(r"acc., \texttt{none}", "qwen3-1.7b-think", "none", "acc"),
             row(r"acc., \texttt{degree}", "qwen3-1.7b-think", "degree", "acc"),
             row(r"\quad enumerates", "qwen3-1.7b-think", "degree",
                 "share_enumerate"),
             row(r"\quad states a discrepancy", "qwen3-1.7b-think", "degree",
                 "discrepancy"),
             r"\midrule",
             r"\multicolumn{%d}{@{}l}{\texttt{qwen3-1.7b}} \\" % (len(dens) + 1),
             row(r"acc., \texttt{none}", "qwen3-1.7b", "none", "acc"),
             row(r"acc., \texttt{degree}", "qwen3-1.7b", "degree", "acc"),
             row(r"\quad retrieves", "qwen3-1.7b", "degree", "share_retrieve"),
             r"\bottomrule", r"\end{tabular}",
             r"\caption{Procedure on \texttt{node\_degree} by density (\%, "
             r"terminated generations). \emph{Retrieves}: the response gives "
             r"the answer without restating the queried node's neighbour "
             r"list. \emph{Enumerates}: it lists the neighbours one per line. "
             r"\emph{States a discrepancy}: it reports that its count and the "
             r"primer disagree. Without a primer every arm counts, so the "
             r"\texttt{none} row is the accuracy of counting.}",
             r"\label{tab:routes}", r"\end{table}"]
    write("v3_routes_table.tex", lines)


if __name__ == "__main__":
    frame = load_frame()
    main_table(frame)
    conditions(frame)
    per_task(frame)
    routes()
